health_check:
  path: /health-check
  controller:  Clickcars\Infrastructure\Driver\Presentation\Controllers\HealthCheckAPIController
  methods: [ GET ]
get_characters:
  path: /getCharacters
  controller:  Clickcars\Infrastructure\Driver\Presentation\Controllers\GetAllCharacters::getAllCharacters
  methods: [ GET ]
get_filtered_characters:
  path: /getFilteredCharacters
  controller:  Clickcars\Infrastructure\Driver\Presentation\Controllers\GetFilteredCharacters::getFilteredCharacters
  methods: [ POST ]